pipeline {
    agent any

    stages {
        stage("Checkout Code") {
            steps {
                git url: "https://github.com/anik007-code1/cicd.git", branch: "main"
            }
        }

        stage("List Files in Root") {
            steps {
                echo "Listing files in the root directory..."
                sh "ls -la"
            }
        }

        stage("List Files in myapp") {
            steps {
                echo "Listing files in the 'myapp' directory..."
                sh "ls -la myapp"
            }
        }

        stage("Validate Files") {
            steps {
                script {
                    if (!fileExists('myapp/jenkins.sh')) {
                        error "File 'jenkins.sh' is missing in the 'myapp' directory!"
                    }
                }
            }
        }

        stage("Install Jenkins") {
            steps {
                dir('myapp') { // Navigate to the myapp directory
                    sh '''
                    echo "Installing Jenkins on the server"
                    chmod +x jenkins.sh
                    ./jenkins.sh
                    '''
                }
            }
        }

        stage("Install Docker") {
            steps {
                dir('myapp') {
                    sh '''
                    echo "Installing Docker on the server"
                    chmod +x docker.sh
                    ./docker.sh
                    '''
                }
            }
        }

        stage("Clone Code") {
            steps {
                dir('myapp') {
                    echo "Cloning the code"
                    git url: "https://github.com/anik007-code1/Django.git", branch: "website"
                }
            }
        }

        stage("Build") {
            steps {
                dir('myapp') {
                    echo "Building the Docker image"
                    sh "docker build -t anikhq ."
                }
            }
        }

//         stage("Push to Docker Hub") {
//             steps {
//                 dir('myapp') {
//                     echo "Pushing the Docker image to Docker Hub"
//                     withCredentials([usernamePassword(credentialsId: "dockerHub", passwordVariable: "dockerHubPass", usernameVariable: "dockerHubUser")]) {
//                         sh "docker tag anikhq ${dockerHubUser}/anikhq:latest"
//                         sh "docker push ${dockerHubUser}/anikhq:latest"
//                     }
//                 }
//             }
//         }

        stage("Deploy Container") {
            steps {
                dir('myapp') {
                    echo "Deploying the container"
                    sh '''
                    docker run -d -p 8000:8000 anikhq:latest
                    '''
                }
            }
        }
    }
}
